name: dson_core
version: 0.13.3
author: Luis Vargas <luisvargastijerino@gmail.com>
description: Convert Objects to Json and Json to Objects
homepage: https://github.com/luisvt/dson_core
environment:
  sdk: '>=2.0.0-dev.60.0'
dependencies:
  source_gen: 
  build: 
  analyzer:
  logging: 
  built_mirrors_core: 
  serializable_core: 
#  serializable_core:
#    path: ../serializable
#  built_mirrors_core:
#    path: ../built_mirrors
#dependency_overrides:
#  built_mirrors:
#    path: ../built_mirrors
